### ISSUE TITLE
Renaming states

### ISSUE THREAD

**Issue by higgs-bosoff** [BernardCloutier/VisualFSM#1]
The plugin works great, but I noticed it seems impossible to rename a State once created - this isn't a big deal per se, but it can be annoying if one is trying to reorganize old code, for example, or notices a typo. Is there any chance to add this functionality?

**Comment by BernardCloutier** [comment]
Added the option to rename states. Just for you pal :P

I haven't touched Godot in a while and wasn't really planning to keep developing this. Out of curiosity, what are you using it for? And what improvements to this plugin would you like to see?
